# Generated by Django 5.0 on 2023-12-09 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=5000)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='images/user_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default='00:00:05')),
                ('end_time', models.TimeField(default='00:00:05')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='doctors.doctorinfo')),
                ('doctor_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorslot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
